version: '3.5'

services:
  app-dev:
    image: wfelipe2011/territorio-digital-development:dev
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 512M
    ports:
      - '5000:5000'
    environment:
      - PORT=$PORT
      - DATABASE_URL=$DATABASE_URL
      - JWT_SECRET=$JWT_SECRET
      - TZ=$TZ
      - LOGTAIL_API_KEY=$LOGTAIL_API_KEY
      - POSTGRES_DB=$POSTGRES_DB
      - NODEMAILER_USER=$NODEMAILER_USER
      - NODEMAILER_APP_PASS=$NODEMAILER_APP_PASS
    networks:
      - default

volumes:
  app-dev:

networks:
  default:
    driver: bridge
