version: '3.5'

services:
  app-prod:
    image: wfelipe2011/territorio-digital-prod:master
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 2G
    networks:
      - npm_public
    ports:
      - '3000:3000'
    volumes:
      - ./public:/app/public

networks:
  npm_public:
    external: true
