version: '3.5'

services:
  app-prod:
    image: wfelipe2011/territorio-digital-prod:master
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 2G
    environment:
      - DATABASE_URL=$DATABASE_URL
      - JWT_SECRET=$JWT_SECRET
      - TZ=$TZ
      - LOGTAIL_API_KEY=$LOGTAIL_API_KEY
      - POSTGRES_DB=$POSTGRES_DB
      - NODEMAILER_USER=$NODEMAILER_USER
      - NODEMAILER_APP_PASS=$NODEMAILER_APP_PASS
    networks:
      - npm_public

volumes:
  app-prod:

networks:
  npm_public:
    external: true
